import type { CockpitTemplate } from './types';

export const marketingTemplate: CockpitTemplate = {
  id: 'marketing',
  name: '营销分析驾驶舱',
  domain: '营销',
  keywords: [
    '营销', '投放', '推广', '广告', 'ROI', '获客', '线索', '品牌',
    '渠道', '转化', '曝光', '点击', '留存', '活跃', '增长',
    'marketing', 'campaign', 'ads', 'acquisition', 'funnel', 'growth',
  ],
  icon: 'Target',
  color: '#ec4899',
  agentIds: ['marketing-agent', 'sales-agent'],
  primaryAgentId: 'marketing-agent',
  description: '整合多渠道营销数据，营销智脑+销售助手联合分析ROI',
  widgets: [
    {
      id: 'w-metric-roi',
      type: 'metric',
      title: '本月ROI',
      position: { x: 0, y: 0, w: 3, h: 2 },
      data: { value: '1:4.2', change: '+12%', trend: 'up' },
      dataSource: {
        type: 'skill',
        skillId: 'marketing.getMonthlyROI',
        agentId: 'marketing-agent',
        transform: '({ roi, change }) => ({ value: `${(roi*100).toFixed(1)}%`, change: `${change>0?"+":""}${(change*100).toFixed(1)}%`, trend: change>0?"up":"down" })',
        fallbackToStatic: true,
      },
    },
    {
      id: 'w-chart-funnel',
      type: 'chart',
      title: '渠道转化漏斗',
      position: { x: 3, y: 0, w: 6, h: 4 },
      data: { labels: ['曝光', '点击', '留资', '试用', '付费'], values: [125000, 8500, 2100, 680, 245] },
      dataSource: {
        type: 'skill',
        skillId: 'marketing.getChannelFunnel',
        agentId: 'marketing-agent',
        transform: '({ labels, values }) => ({ labels, values })',
        fallbackToStatic: true,
      },
    },
    {
      id: 'w-table-channels',
      type: 'table',
      title: '渠道表现',
      position: { x: 0, y: 2, w: 3, h: 4 },
      data: { rows: [['抖音', '¥45万', '1:5.2'], ['百度', '¥32万', '1:3.8'], ['微信', '¥28万', '1:4.5'], ['小红书', '¥18万', '1:6.1'], ['知乎', '¥12万', '1:3.2']] },
      dataSource: {
        type: 'skill',
        skillId: 'marketing.getChannelPerformance',
        agentId: 'marketing-agent',
        input: { limit: 5 },
        transform: '({ rows }) => ({ rows })',
        fallbackToStatic: true,
      },
    },
    {
      id: 'w-metric-cac',
      type: 'metric',
      title: '获客成本',
      position: { x: 9, y: 0, w: 3, h: 2 },
      data: { value: '¥320', change: '-8%', trend: 'up' },
      dataSource: {
        type: 'skill',
        skillId: 'marketing.getCustomerAcquisitionCost',
        agentId: 'marketing-agent',
        transform: '({ cac, change }) => ({ value: `¥${cac.toFixed(0)}`, change: `${change>0?"+":""}${(change*100).toFixed(1)}%`, trend: change>0?"up":"down" })',
        fallbackToStatic: true,
      },
    },
  ],
};
