import type { CockpitTemplate } from './types';

export const salesTemplate: CockpitTemplate = {
  id: 'sales',
  name: '销售业绩驾驶舱',
  domain: '销售',
  keywords: [
    '销售', '业绩', '营收', '订单', '客户', '转化', '漏斗', 'CRM',
    '销售额', '成交', '线索', '商机', '客单价', '回款',
    'sales', 'revenue', 'deal', 'pipeline', 'conversion', 'quota',
  ],
  icon: 'BarChart3',
  color: '#6366f1',
  agentIds: ['sales-agent', 'marketing-agent'],
  primaryAgentId: 'sales-agent',
  description: '实时展示{{name}}数据、业绩趋势和客户排行，由销售助手+营销智脑联合驱动',
  widgets: [
    {
      id: 'w-metric-sales',
      type: 'metric',
      title: '本月销售额',
      position: { x: 0, y: 0, w: 3, h: 2 },
      data: { value: '¥1,250万', change: '+18.5%', trend: 'up' },
      dataSource: {
        type: 'skill',
        skillId: 'sales.getMonthlyRevenue',
        agentId: 'sales-agent',
        input: { timeRange: 'thisMonth' },
        transform: '({ revenue, growth }) => ({ value: `¥${(revenue/1e4).toFixed(0)}万`, change: `${growth>0?"+":""}${(growth*100).toFixed(0)}%`, trend: growth>0?"up":"down" })',
        fallbackToStatic: true,
      },
    },
    {
      id: 'w-chart-trend',
      type: 'chart',
      title: '业绩趋势',
      position: { x: 3, y: 0, w: 6, h: 4 },
      data: { labels: ['1月', '2月', '3月', '4月', '5月', '6月'], values: [820, 950, 880, 1120, 1080, 1250] },
      dataSource: {
        type: 'skill',
        skillId: 'sales.getRevenueTrend',
        agentId: 'sales-agent',
        input: { months: 6 },
        transform: '({ labels, values }) => ({ labels, values })',
        fallbackToStatic: true,
      },
    },
    {
      id: 'w-table-top',
      type: 'table',
      title: 'Top 5 客户',
      position: { x: 0, y: 2, w: 3, h: 4 },
      data: { rows: [['华为云', '¥320万', '续签'], ['阿里云', '¥280万', '新增'], ['腾讯云', '¥210万', '扩容'], ['字节跳动', '¥180万', '新增'], ['美团', '¥150万', '续签']] },
      dataSource: {
        type: 'skill',
        skillId: 'sales.getTopCustomers',
        agentId: 'sales-agent',
        input: { limit: 5 },
        transform: '({ rows }) => ({ rows })',
        fallbackToStatic: true,
      },
    },
    {
      id: 'w-metric-rate',
      type: 'metric',
      title: '订单转化率',
      position: { x: 9, y: 0, w: 3, h: 2 },
      data: { value: '24.8%', change: '+3.2%', trend: 'up' },
      dataSource: {
        type: 'skill',
        skillId: 'sales.getConversionRate',
        agentId: 'sales-agent',
        input: { timeRange: 'thisMonth' },
        transform: '({ rate, change }) => ({ value: `${(rate*100).toFixed(1)}%`, change: `${change>0?"+":""}${(change*100).toFixed(1)}%`, trend: change>0?"up":"down" })',
        fallbackToStatic: true,
      },
    },
    {
      id: 'w-kanban-funnel',
      type: 'kanban',
      title: '销售漏斗',
      position: { x: 9, y: 2, w: 3, h: 4 },
      data: { stages: ['线索', '接触', '确认', '谈判', '成交'] },
      dataSource: {
        type: 'skill',
        skillId: 'sales.getPipelineStages',
        agentId: 'sales-agent',
        transform: '({ stages }) => ({ stages })',
        fallbackToStatic: true,
      },
    },
  ],
};
